# Generated by Django 5.0.1 on 2024-01-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Image', models.ImageField(help_text='Image size must be 1080px', upload_to='demo')),
            ],
        ),
    ]
