# Generated by Django 5.0.1 on 2024-01-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True),
        ),
    ]
