# Generated by Django 5.0.1 on 2024-01-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_demomodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='Description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
    ]
