# Generated by Django 5.0.1 on 2024-01-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_demomodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='Availability',
            field=models.BooleanField(default=True, help_text='Is the product available?'),
        ),
    ]
